kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: device-registry
type: Opaque
stringData:
  admin.username: admin
  admin.password: admin123456
