kind: Service
apiVersion: v1
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: device-registry
spec:
  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: device-management-service
    app.kubernetes.io/part-of: device-registry
  type: ClusterIP
