kind: Service
apiVersion: v1
metadata:
  name: command-endpoint
  labels:
    app.kubernetes.io/name: command-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    app.kubernetes.io/name: command-endpoint
    app.kubernetes.io/part-of: endpoints
  ports:
    - name: endpoint
      protocol: TCP
      port: 8080
      targetPort: endpoint
  type: {{ include "drogue-cloud-core.service.passthrough.type" . }}
