{{ if eq .Values.cluster "openshift" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqtt-endpoint
spec:
  to:
    kind: Service
    name: mqtt-endpoint
  port:
    targetPort: endpoint
  tls:
    termination: passthrough
{{- end }}
