---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: iot-events
  config: {}
  partitions: 3
  replicas: 1
  topicName: iot-events
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: iot-commands
  config: {}
  partitions: 3
  replicas: 1
  topicName: iot-events
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: registry
  config: {}
  partitions: 3
  replicas: 1
  topicName: iot-events
