apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base/configuration
  - ../base/kafka
  - ../base/knative
  - sso
  - source/mqtt
  - source/http
  #- source/http-insecure
  - source/command
  - ../base/service/influxdb
  - service/grafana
  - service/console
  - service/registry
  - integration/mqtt
  - ../base/api
