kind: Service
apiVersion: v1
metadata:
  name: http-endpoint
  labels:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
spec:
  selector:
    app.kubernetes.io/name: http-endpoint
    app.kubernetes.io/part-of: endpoints
  ports:
    - name: endpoint
      port: {{ if .Values.endpoints.http.insecure }}8080{{ else }}443{{ end }}
      protocol: TCP
      targetPort: endpoint
  type: {{ include "drogue-cloud-core.service.passthrough.type" . }}