apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: commands-mqtt
  labels:
    app.kubernetes.io/part-of: endpoints
spec:
  consumerGroup: commands-mqtt
  bootstrapServers:
    - drogue-iot-kafka-bootstrap:9092
  topics:
    - iot-commands
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: mqtt-command
    uri: /command-service
